### ISSUE TITLE
Error: Cannot find module 'F:\webpack\bin\webpack.js'

### ISSUE THREAD

**Issue by LarryEitel** [lancetw/react-isomorphic-bundle#3]
I am very intrigued with your package. I have installed everything. I only had to replace the `bcrypt` dependency with `"co-bcryptjs": "^0.2.0"` to avoid hassle of trying to build bcrypt on `Windows`.

So I run `npm run build` and it returns:
```
F:\_vms\HomesteadCode\_live\misc\react-isomorphic-bundle>npm run build

> react-isomorphic-bundle@0.0.1 build F:\_vms\HomesteadCode\_live\misc\react-isomorphic-bundle
> make build

      0 [main] find 14868 open_stackdumpfile: Dumping stack trace to find.exe.stackdump
      0 [main] find 14836 open_stackdumpfile: Dumping stack trace to find.exe.stackdump
      0 [main] find 14908 open_stackdumpfile: Dumping stack trace to find.exe.stackdump
      0 [main] find 14952 open_stackdumpfile: Dumping stack trace to find.exe.stackdump
      0 [main] find 14972 open_stackdumpfile: Dumping stack trace to find.exe.stackdump
      0 [main] dirname 15020 open_stackdumpfile: Dumping stack trace to dirname.exe.stackdump
      0 [main] uname 15100 open_stackdumpfile: Dumping stack trace to uname.exe.stackdump
module.js:338
    throw err;
          ^
Error: Cannot find module 'F:\webpack\bin\webpack.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
make: *** [public/assets] Error 1

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "F:\\Program Files\\nodejs\\\\node.exe" "F:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! react-isomorphic-bundle@0.0.1 build: `make build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the react-isomorphic-bundle@0.0.1 build script 'make build'.
npm ERR! This is most likely a problem with the react-isomorphic-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make build
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-isomorphic-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\_vms\HomesteadCode\_live\misc\react-isomorphic-bundle\npm-debug.log
```

**Comment by lancetw** [comment]
Hi @LarryEitel,

This project will finally work on Windows, but I'm not testing the Makefile for now.

If you want this project works on Windows, all problems will about "paths" (babel maybe not working if the IIS temp dictrectoy has permission issues),
see the last line of Makefile:
`public/assets: $(SRC_JS)
	@NODE_ENV=production $(BIN)/webpack --progress --profile --colors --stats --config webpack/server.js`

**Comment by lancetw** [comment]
If you want a small and stable example to work, see: https://github.com/rackt/redux/tree/master/examples/real-world

**Comment by lancetw** [comment]
I have modified makefile and now can run on Windows (Git Bash).
